### ISSUE TITLE
Create Class Diagram

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#107]
## Description

This task includes creating a class diagram. The task should include cooperation of all subteams. Please open an individual page for the diagram.

***

### Reviewer:
This issue will be reviewed by: _@ArdaYalcindag_

**Comment by ounuvar** [comment]
Sorry, I closed the issue by mistake. Could you review the class diagram @ArdaYalcindag ?

**Comment by ArdaYalcindag** [comment]
I have reviewed the diagram. Here are some questions about the diagram:
* Not all classes have methods section filled. Assuming that you are planning to update and enhance those parts while developing, Am I right?
* Relations between classes are very few. For instance only games have reviews, right?
* I couldn't find how someone can add a game to a custom **list**. **Game** class should be more detailed I think. What are your thoughts?

**Comment by ounuvar** [comment]
- Some classes don't have methods because they are essentially behaviorless. Some people call these Plain Old Data Types (POD): https://en.wikipedia.org/wiki/Passive_data_structure. Other classes (like the RegisteredUser class, the Profile class, or the Admin class) act on them.
- I now added all the composition (has) relationships. Could you check it again?
- There is the "+addGameToList(list: List, game: Game): Result" method under RegisteredUser. Here the "list" argument is either the default Playlist or a custom list. Can you clarify what you mean by more detailed? Do you mean more fields or more methods? Games are mostly passive pieces of data. RegisteredUsers like them, review them, or add them to their lists. All of these have their corresponding methods under the RegisteredUser class. If you mean more fields, could you point out which fields you think are missing?

**Comment by ArdaYalcindag** [comment]
Thanks for detailed answers, it looks fine for me now. Nothing more comes to my mind. If you have something to add, let me know. I will close this issue tomorrow.

**Comment by ounuvar** [comment]
- I added an extra enum called Extras that hold extra WikiData properties that can be displayed on each game's page (this will be an extra tab next to "Game, Characters, Credits, Reviews" on mobile, and either the same way on web or a separate sidebar). This enum can be extended (and the corresponding Game class fields) as we keep seeing other relevant properties on WikiData that we could use. The mobile and frontend code will use this enum to decide which views to try to generate when displaying the extras information for a game. Not all extras might be available for each game, so there needs to be null checking on the corresponding fields of that Game instance as well.

- I included a "banner" field to the Game class which I was missing before. This holds the banner image that we can see at the top of each game page or on the main page when the game is selected as the "Game of the Day".

Other than these, I can't think of any other changes/additions I need to make. You can close the issue after reviewing it once more. If anything else come up again, I will reopen the issue and mention it here.

**Comment by asyasusen** [comment]
Everything seems okay. I've just added lastEditDate and likedBy list of registeredUsers.

**Comment by ahmetfirat23** [comment]
Seems good to me too. Feel free to reopen if anything comes up to your mind.
