### ISSUE TITLE
Initialize the Frontend side of the project

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#118]
## Description

Initialize the React Project with create-react-app. Commit the changes to the frontend-dev branch.

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by sonerkuyar** [comment]
I created the frontend-dev branch and react-app. I didn't organize the app file structure yet. Please wait for me to organize file structures and set the theme (fonts, color, etc..).  [Commit for Create React app](https://github.com/bounswe/bounswe2024group12/commit/86e309e9931038abfc87f519e3adf5d7e041d367l)

**Comment by sonerkuyar** [comment]
I added the fonts.css and globals.css files and also organize the file structure(deleted test related files and unnecessary starter pack files). All components should be compatible with the globals.css file these styles will be implemented through whole app unless you specify new properties or overwrite the existing ones. 
You can override the globals.css file inside your components. 
If you think that anything should be added the globals.css file and maintained through the whole app, instead of changing the component style in every time, I encourage you to edit globals.css file.  
Here is the related commit [Commit for adding styles](https://github.com/bounswe/bounswe2024group12/commit/8de2ed6d31d091a263f22e5ae2449305846bb54b)

**Comment by sonerkuyar** [comment]
@ahmetfirat23  I'm done with this issue. Could you check and run the app on your local ?

**Comment by ahmetfirat23** [comment]
> @ahmetfirat23 I'm done with this issue. Could you check and run the app on your local ?

It works alright on my local too.
