### ISSUE TITLE
UseEffect Being Called Twice Bug

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#170]
## Description

When we use UseEffect with empty array it is being called twice. This is a problem because we are making API calls in those calls. I located that   <React.StrictMode> in index.js is causing this issue. Removing this fixes the problem; however, it raises "Each child in a list should have a unique "key" prop." issues. I am not sure what exactly is StrictMode. Please check what is it, should we remove it or what could we do about it to fix this problem.

***

## Acceptance Criteria
- [x] Strict Mode should be shortly explained in the comments
- [ ] Twice calling issue should be fixed.
<br>

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by asyasusen** [comment]
>     Strict Mode enables the following development-only behaviors:
> 
>         Your components will re-render an extra time to find bugs caused by impure rendering.
>         Your components will re-run Effects an extra time to find bugs caused by missing Effect cleanup.
>         Your components will be checked for usage of deprecated APIs.

When you have the Strict Mode enabled, React performs additional runtime checks in the development environment to make sure your app is safe and sound. This also includes every component getting mounted (causing useEffect to be executed), unmounted, and finally mounted again (causing useEffect to be executed a second time). React does this to check that your effects are resilient to remounting, so that that certain behind-the-scene optimizations can be performed safely. I've read the official React blogpost about a similar issue and it says "In development, logVisit will be called twice for every URL, so you might be tempted to try to work around it. We recommend to keep this code as is. Like with earlier examples, there is no user-visible behavior difference between running it once and running it twice. From a practical point of view, logVisit should not do anything in development because you don’t want the logs from the development machines to skew the production metrics.". Since it behaves differently in development mode than it does with a production build (behind the scenes they also mess with the console logs, so that those don’t appear twice),  I think it is fine to leave it as it is. Basically from what I understand it has to do with behind the scene React optimizations and they recommend leaving it as it is. If you are convinced I will close this issue

**Comment by ahmetfirat23** [comment]
I got it, then to fix this twice calling issue (so it turns out it is not a bug exactly) we just need to take a production build. Cool.
