### ISSUE TITLE
Change deployment protocol from http to https

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#189]
## Description

As mentioned in parent issue, this is needed because of IGDB API usage.

***

## Acceptance Criteria
- [x] Our project is deployed in https protocol instead of http.
<br>

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu @yusufaygun

**Comment by isilsukarakuzuu** [comment]
@yusufaygun @e-taha guys I also added you since you also have knowledge about digital ocean, fyi

**Comment by ahmetfirat23** [comment]
This task was difficult than I thought. I couldn't get self signed SSL protocol running with backend and frontend. We should postpone this and IGDB requests since there are more important functionalities need to be implemented. Also if anyone willing to open up a free domain with student pack perks (though still requires credit card info) I think we can much more easily finish up this task. @bounswe/bounswe2024group12

**Comment by isilsukarakuzuu** [comment]
We didn't use any IGDB queries so far, so It's fine, let's do this after this milestone.

**Comment by ahmetfirat23** [comment]
I believe we changed backend to a secure protocol for mobile team. If we had time maybe we could use IGDB too using that. For now I think this issue is complete.

**Comment by ounuvar** [comment]
@e-taha and I managed to get a free domain with an SSL certificate from name.com through the GitHub student pack. Then we reconfigured the Nginx server in our DigitalOcean droplet with the SSL certificate to enable https. Our web frontend deployment still uses the http protocol though. We used the new domain name to enable our mobile app to run on Android and be able to make API calls to the backend. The new domain can be accessed at https://playlog.games, though it only redirects to port 8000 for now (the backend). I might reconfigure the Nginx server again after the grading, so https://playlog.games immediately redirects to the frontend website.
