### ISSUE TITLE
Implement Advanced Search

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#217]
## Description

We need to implement advanced search for our project.

***

## Acceptance Criteria
- [x] Change search from exact match to prefix search.
- [x] Add search filters.
<br>

***

### Reviewer:
This issue will be reviewed by: @sonerkuyar

**Comment by isilsukarakuzuu** [comment]
I changed the search from exact-match to prefix search. Now we can return up to 10 solutions that starts with the search key.

**Comment by isilsukarakuzuu** [comment]
@sonerkuyar let's discuss our additions here.

**Comment by isilsukarakuzuu** [comment]
@sonerkuyar added search by filters and I added property search, this issue is done now.

**Comment by sonerkuyar** [comment]
Due to I implemented also frontend of Advanced Searching, Im adding also Frontend Label to this issue. Here is the quick recap of my developments.
- [ ] First Dynamic implementation of backend and frontend for Advance Searching. [Commit Link](https://github.com/bounswe/bounswe2024group12/commit/d181d5369d749b12a282354a6f770b03cf713dd6)
- [ ] Debouncing and Abort Fetch mechanism for responsiveness. [Commit Link](https://github.com/bounswe/bounswe2024group12/commit/dbc7f9def2803c9bc3af53b240d5093e9f498d27)
- [ ] Unifying, refinement and bug fix for mechanic of Advance search. [1](50d9dda066b8d58739795921b0a9fed236edaec3), [2](5924741400c2fa71c248d31c32f7e0d3662e6e16), [3](https://github.com/bounswe/bounswe2024group12/commit/129a4474d77e6a72607f290ed0e1408240217643)
- [ ] User search for frontend. [Commit Link](https://github.com/bounswe/bounswe2024group12/commit/05c4076ca3f80c5561d270bd9068875b547f5019)
