### ISSUE TITLE
Backend: Implement Bookmarking Feature

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#366]
## Description

Posts, games and game moves will be bookmarkable, so that user can revisit its bookmarked elements.

***

## Acceptance Criteria
- [x] Database keeps the bookmarked flag for user at appropriate models.
- [x] Endpoint returns bookmarked items successfully for authenticated users
- [x] Endpoint documented with examples.
- [x] Unit Tests created and run for the endpoint.
<br>...

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by yusufaygun** [comment]
All tasks related to this issue have been completed.

- Bookmark models for posts, games, and game moves have been created with the appropriate user relationships.
- Toggle endpoints for post, game, and game move bookmarks have been implemented.
- Swagger documentation for all bookmark endpoints has been added.
- Comprehensive unit tests have been written and successfully executed for all bookmark functionalities.

This issue is now ready for review. @ahmetfirat23
